/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IdentityVerifier } from "./IdentityVerifier";
export type { ZKPQueriesStorage } from "./ZKPQueriesStorage";
export * as factories from "./factories";
export { IdentityVerifier__factory } from "./factories/IdentityVerifier__factory";
export { ZKPQueriesStorage__factory } from "./factories/ZKPQueriesStorage__factory";
