/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export declare namespace ISBTIdentityVerifier {
  export type SBTIdentityProofInfoStruct = {
    senderAddr: string;
    sbtTokenId: BigNumberish;
    isProved: boolean;
  };

  export type SBTIdentityProofInfoStructOutput = [
    string,
    BigNumber,
    boolean
  ] & { senderAddr: string; sbtTokenId: BigNumber; isProved: boolean };
}

export declare namespace ILightweightState {
  export type StatesMerkleDataStruct = {
    issuerId: BigNumberish;
    issuerState: BigNumberish;
    createdAtTimestamp: BigNumberish;
    merkleProof: BytesLike[];
  };

  export type StatesMerkleDataStructOutput = [
    BigNumber,
    BigNumber,
    BigNumber,
    string[]
  ] & {
    issuerId: BigNumber;
    issuerState: BigNumber;
    createdAtTimestamp: BigNumber;
    merkleProof: string[];
  };

  export type GistRootDataStruct = {
    root: BigNumberish;
    createdAtTimestamp: BigNumberish;
  };

  export type GistRootDataStructOutput = [BigNumber, BigNumber] & {
    root: BigNumber;
    createdAtTimestamp: BigNumber;
  };
}

export declare namespace IBaseVerifier {
  export type ProveIdentityParamsStruct = {
    statesMerkleData: ILightweightState.StatesMerkleDataStruct;
    inputs: BigNumberish[];
    a: [BigNumberish, BigNumberish];
    b: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]];
    c: [BigNumberish, BigNumberish];
  };

  export type ProveIdentityParamsStructOutput = [
    ILightweightState.StatesMerkleDataStructOutput,
    BigNumber[],
    [BigNumber, BigNumber],
    [[BigNumber, BigNumber], [BigNumber, BigNumber]],
    [BigNumber, BigNumber]
  ] & {
    statesMerkleData: ILightweightState.StatesMerkleDataStructOutput;
    inputs: BigNumber[];
    a: [BigNumber, BigNumber];
    b: [[BigNumber, BigNumber], [BigNumber, BigNumber]];
    c: [BigNumber, BigNumber];
  };

  export type TransitStateParamsStruct = {
    newIdentitiesStatesRoot: BytesLike;
    gistData: ILightweightState.GistRootDataStruct;
    proof: BytesLike;
  };

  export type TransitStateParamsStructOutput = [
    string,
    ILightweightState.GistRootDataStructOutput,
    string
  ] & {
    newIdentitiesStatesRoot: string;
    gistData: ILightweightState.GistRootDataStructOutput;
    proof: string;
  };
}

export interface SBTIdentityVerifierInterface extends utils.Interface {
  functions: {
    "SBT_IDENTITY_PROOF_QUERY_ID()": FunctionFragment;
    "__SBTIdentityVerifier_init(address,address)": FunctionFragment;
    "addressToIdentityId(address)": FunctionFragment;
    "getAllowedIssuers(uint256)": FunctionFragment;
    "getIdentityProofInfo(uint256)": FunctionFragment;
    "isAllowedIssuer(uint256,uint256)": FunctionFragment;
    "isIdentityProved(address)": FunctionFragment;
    "isIdentityProved(uint256)": FunctionFragment;
    "owner()": FunctionFragment;
    "proveIdentity(((uint256,uint256,uint256,bytes32[]),uint256[],uint256[2],uint256[2][2],uint256[2]))": FunctionFragment;
    "proxiableUUID()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "sbtToken()": FunctionFragment;
    "setZKPQueriesStorage(address)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "transitStateAndProveIdentity(((uint256,uint256,uint256,bytes32[]),uint256[],uint256[2],uint256[2][2],uint256[2]),(bytes32,(uint256,uint256),bytes))": FunctionFragment;
    "updateAllowedIssuers(uint256,uint256[],bool)": FunctionFragment;
    "upgradeTo(address)": FunctionFragment;
    "upgradeToAndCall(address,bytes)": FunctionFragment;
    "zkpQueriesStorage()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "SBT_IDENTITY_PROOF_QUERY_ID"
      | "__SBTIdentityVerifier_init"
      | "addressToIdentityId"
      | "getAllowedIssuers"
      | "getIdentityProofInfo"
      | "isAllowedIssuer"
      | "isIdentityProved(address)"
      | "isIdentityProved(uint256)"
      | "owner"
      | "proveIdentity"
      | "proxiableUUID"
      | "renounceOwnership"
      | "sbtToken"
      | "setZKPQueriesStorage"
      | "transferOwnership"
      | "transitStateAndProveIdentity"
      | "updateAllowedIssuers"
      | "upgradeTo"
      | "upgradeToAndCall"
      | "zkpQueriesStorage"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "SBT_IDENTITY_PROOF_QUERY_ID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "__SBTIdentityVerifier_init",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "addressToIdentityId",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllowedIssuers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getIdentityProofInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isAllowedIssuer",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isIdentityProved(address)",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "isIdentityProved(uint256)",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "proveIdentity",
    values: [IBaseVerifier.ProveIdentityParamsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "sbtToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setZKPQueriesStorage",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "transitStateAndProveIdentity",
    values: [
      IBaseVerifier.ProveIdentityParamsStruct,
      IBaseVerifier.TransitStateParamsStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "updateAllowedIssuers",
    values: [BigNumberish, BigNumberish[], boolean]
  ): string;
  encodeFunctionData(functionFragment: "upgradeTo", values: [string]): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "zkpQueriesStorage",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "SBT_IDENTITY_PROOF_QUERY_ID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "__SBTIdentityVerifier_init",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addressToIdentityId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllowedIssuers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getIdentityProofInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isAllowedIssuer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isIdentityProved(address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isIdentityProved(uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proveIdentity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sbtToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setZKPQueriesStorage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transitStateAndProveIdentity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateAllowedIssuers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "upgradeTo", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "zkpQueriesStorage",
    data: BytesLike
  ): Result;

  events: {
    "AdminChanged(address,address)": EventFragment;
    "BeaconUpgraded(address)": EventFragment;
    "Initialized(uint8)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "SBTIdentityProved(uint256,address,address,uint256)": EventFragment;
    "Upgraded(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AdminChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BeaconUpgraded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SBTIdentityProved"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Upgraded"): EventFragment;
}

export interface AdminChangedEventObject {
  previousAdmin: string;
  newAdmin: string;
}
export type AdminChangedEvent = TypedEvent<
  [string, string],
  AdminChangedEventObject
>;

export type AdminChangedEventFilter = TypedEventFilter<AdminChangedEvent>;

export interface BeaconUpgradedEventObject {
  beacon: string;
}
export type BeaconUpgradedEvent = TypedEvent<
  [string],
  BeaconUpgradedEventObject
>;

export type BeaconUpgradedEventFilter = TypedEventFilter<BeaconUpgradedEvent>;

export interface InitializedEventObject {
  version: number;
}
export type InitializedEvent = TypedEvent<[number], InitializedEventObject>;

export type InitializedEventFilter = TypedEventFilter<InitializedEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface SBTIdentityProvedEventObject {
  identityId: BigNumber;
  senderAddr: string;
  tokenAddr: string;
  tokenID: BigNumber;
}
export type SBTIdentityProvedEvent = TypedEvent<
  [BigNumber, string, string, BigNumber],
  SBTIdentityProvedEventObject
>;

export type SBTIdentityProvedEventFilter =
  TypedEventFilter<SBTIdentityProvedEvent>;

export interface UpgradedEventObject {
  implementation: string;
}
export type UpgradedEvent = TypedEvent<[string], UpgradedEventObject>;

export type UpgradedEventFilter = TypedEventFilter<UpgradedEvent>;

export interface SBTIdentityVerifier extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: SBTIdentityVerifierInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    SBT_IDENTITY_PROOF_QUERY_ID(overrides?: CallOverrides): Promise<[string]>;

    __SBTIdentityVerifier_init(
      zkpQueriesStorage_: string,
      sbtToken_: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    addressToIdentityId(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getAllowedIssuers(
      schema_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber[]]>;

    getIdentityProofInfo(
      identityId_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[ISBTIdentityVerifier.SBTIdentityProofInfoStructOutput]>;

    isAllowedIssuer(
      schema_: BigNumberish,
      issuerId_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "isIdentityProved(address)"(
      userAddr_: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "isIdentityProved(uint256)"(
      identityId_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    proveIdentity(
      proveIdentityParams_: IBaseVerifier.ProveIdentityParamsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    proxiableUUID(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    sbtToken(overrides?: CallOverrides): Promise<[string]>;

    setZKPQueriesStorage(
      newZKPQueriesStorage_: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    transitStateAndProveIdentity(
      proveIdentityParams_: IBaseVerifier.ProveIdentityParamsStruct,
      transitStateParams_: IBaseVerifier.TransitStateParamsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    updateAllowedIssuers(
      schema_: BigNumberish,
      issuerIds_: BigNumberish[],
      isAdding_: boolean,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    upgradeTo(
      newImplementation: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    upgradeToAndCall(
      newImplementation: string,
      data: BytesLike,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    zkpQueriesStorage(overrides?: CallOverrides): Promise<[string]>;
  };

  SBT_IDENTITY_PROOF_QUERY_ID(overrides?: CallOverrides): Promise<string>;

  __SBTIdentityVerifier_init(
    zkpQueriesStorage_: string,
    sbtToken_: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  addressToIdentityId(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getAllowedIssuers(
    schema_: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber[]>;

  getIdentityProofInfo(
    identityId_: BigNumberish,
    overrides?: CallOverrides
  ): Promise<ISBTIdentityVerifier.SBTIdentityProofInfoStructOutput>;

  isAllowedIssuer(
    schema_: BigNumberish,
    issuerId_: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "isIdentityProved(address)"(
    userAddr_: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "isIdentityProved(uint256)"(
    identityId_: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  owner(overrides?: CallOverrides): Promise<string>;

  proveIdentity(
    proveIdentityParams_: IBaseVerifier.ProveIdentityParamsStruct,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  proxiableUUID(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  sbtToken(overrides?: CallOverrides): Promise<string>;

  setZKPQueriesStorage(
    newZKPQueriesStorage_: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  transitStateAndProveIdentity(
    proveIdentityParams_: IBaseVerifier.ProveIdentityParamsStruct,
    transitStateParams_: IBaseVerifier.TransitStateParamsStruct,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  updateAllowedIssuers(
    schema_: BigNumberish,
    issuerIds_: BigNumberish[],
    isAdding_: boolean,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  upgradeTo(
    newImplementation: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  upgradeToAndCall(
    newImplementation: string,
    data: BytesLike,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  zkpQueriesStorage(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    SBT_IDENTITY_PROOF_QUERY_ID(overrides?: CallOverrides): Promise<string>;

    __SBTIdentityVerifier_init(
      zkpQueriesStorage_: string,
      sbtToken_: string,
      overrides?: CallOverrides
    ): Promise<void>;

    addressToIdentityId(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAllowedIssuers(
      schema_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    getIdentityProofInfo(
      identityId_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<ISBTIdentityVerifier.SBTIdentityProofInfoStructOutput>;

    isAllowedIssuer(
      schema_: BigNumberish,
      issuerId_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "isIdentityProved(address)"(
      userAddr_: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "isIdentityProved(uint256)"(
      identityId_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    owner(overrides?: CallOverrides): Promise<string>;

    proveIdentity(
      proveIdentityParams_: IBaseVerifier.ProveIdentityParamsStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    proxiableUUID(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    sbtToken(overrides?: CallOverrides): Promise<string>;

    setZKPQueriesStorage(
      newZKPQueriesStorage_: string,
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    transitStateAndProveIdentity(
      proveIdentityParams_: IBaseVerifier.ProveIdentityParamsStruct,
      transitStateParams_: IBaseVerifier.TransitStateParamsStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    updateAllowedIssuers(
      schema_: BigNumberish,
      issuerIds_: BigNumberish[],
      isAdding_: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    upgradeTo(
      newImplementation: string,
      overrides?: CallOverrides
    ): Promise<void>;

    upgradeToAndCall(
      newImplementation: string,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    zkpQueriesStorage(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "AdminChanged(address,address)"(
      previousAdmin?: null,
      newAdmin?: null
    ): AdminChangedEventFilter;
    AdminChanged(
      previousAdmin?: null,
      newAdmin?: null
    ): AdminChangedEventFilter;

    "BeaconUpgraded(address)"(
      beacon?: string | null
    ): BeaconUpgradedEventFilter;
    BeaconUpgraded(beacon?: string | null): BeaconUpgradedEventFilter;

    "Initialized(uint8)"(version?: null): InitializedEventFilter;
    Initialized(version?: null): InitializedEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;

    "SBTIdentityProved(uint256,address,address,uint256)"(
      identityId?: BigNumberish | null,
      senderAddr?: null,
      tokenAddr?: null,
      tokenID?: null
    ): SBTIdentityProvedEventFilter;
    SBTIdentityProved(
      identityId?: BigNumberish | null,
      senderAddr?: null,
      tokenAddr?: null,
      tokenID?: null
    ): SBTIdentityProvedEventFilter;

    "Upgraded(address)"(implementation?: string | null): UpgradedEventFilter;
    Upgraded(implementation?: string | null): UpgradedEventFilter;
  };

  estimateGas: {
    SBT_IDENTITY_PROOF_QUERY_ID(overrides?: CallOverrides): Promise<BigNumber>;

    __SBTIdentityVerifier_init(
      zkpQueriesStorage_: string,
      sbtToken_: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    addressToIdentityId(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAllowedIssuers(
      schema_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getIdentityProofInfo(
      identityId_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isAllowedIssuer(
      schema_: BigNumberish,
      issuerId_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "isIdentityProved(address)"(
      userAddr_: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "isIdentityProved(uint256)"(
      identityId_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    proveIdentity(
      proveIdentityParams_: IBaseVerifier.ProveIdentityParamsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    proxiableUUID(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    sbtToken(overrides?: CallOverrides): Promise<BigNumber>;

    setZKPQueriesStorage(
      newZKPQueriesStorage_: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    transitStateAndProveIdentity(
      proveIdentityParams_: IBaseVerifier.ProveIdentityParamsStruct,
      transitStateParams_: IBaseVerifier.TransitStateParamsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    updateAllowedIssuers(
      schema_: BigNumberish,
      issuerIds_: BigNumberish[],
      isAdding_: boolean,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    upgradeTo(
      newImplementation: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    upgradeToAndCall(
      newImplementation: string,
      data: BytesLike,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    zkpQueriesStorage(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    SBT_IDENTITY_PROOF_QUERY_ID(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    __SBTIdentityVerifier_init(
      zkpQueriesStorage_: string,
      sbtToken_: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    addressToIdentityId(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAllowedIssuers(
      schema_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getIdentityProofInfo(
      identityId_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isAllowedIssuer(
      schema_: BigNumberish,
      issuerId_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "isIdentityProved(address)"(
      userAddr_: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "isIdentityProved(uint256)"(
      identityId_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    proveIdentity(
      proveIdentityParams_: IBaseVerifier.ProveIdentityParamsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    proxiableUUID(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    sbtToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setZKPQueriesStorage(
      newZKPQueriesStorage_: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    transitStateAndProveIdentity(
      proveIdentityParams_: IBaseVerifier.ProveIdentityParamsStruct,
      transitStateParams_: IBaseVerifier.TransitStateParamsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    updateAllowedIssuers(
      schema_: BigNumberish,
      issuerIds_: BigNumberish[],
      isAdding_: boolean,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    upgradeTo(
      newImplementation: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    upgradeToAndCall(
      newImplementation: string,
      data: BytesLike,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    zkpQueriesStorage(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
