/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { DemoVerifier__factory } from "./DemoVerifier__factory";
export { ZKPQueriesStorage__factory } from "./ZKPQueriesStorage__factory";
