on:
  push:
    branches:
      - 'main'

jobs:
  converge:
    name: Converge
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install werf
        uses: werf/actions/install@v1.2

      - name: Log in to registry
        # This is where you will update the personal access token to GITHUB_TOKEN
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Run echo
        run: |
          werf version
          docker version
          echo $GITHUB_REPOSITORY
          echo $GITHUB_SHA
      - name: Run Build
        env: # Or as an environment variable
          VITE_SENTRY_AUTH_TOKEN: ${{ secrets.VITE_SENTRY_AUTH_TOKEN }}
          VITE_SENTRY_DSN: ${{ secrets.VITE_SENTRY_DSN }}
          VITE_APP_DOMAIN: https://robotornot.mainnet-beta.rarimo.com
        run: |
          cp .env-development .env
          . $(werf ci-env github --as-file)
          werf export --dev web --tag ghcr.io/$GITHUB_REPOSITORY:$GITHUB_SHA

  deploy:
      name: Deploy
      needs: converge
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - name: ConfigCreate
          run: |
            mkdir ~/.kube/
            echo "${{ secrets.K8SCONFIG_DEV }}" | base64 -d > config
            mv config ~/.kube/
            kubectl set image deployment rarimo-web template=ghcr.io/$GITHUB_REPOSITORY:$GITHUB_SHA -n unstopable
